# Generated by Django 4.0.6 on 2022-07-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redirect',
            name='key',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
